export const API_ERROR_CODES = {
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
};

export const STATUS_LIST_LIMIT = 1000;
