export const DASHBOARD_COPY = {
  heroTitle: 'Regional Satellite Monitoring',
  heroSubtitle: 'West Java Environmental Surveillance Platform',
  systemOnline: 'System Online',
  mapLoading: 'Loading map...',
  lastUpdatedLabel: 'Last Updated:',
  totalForestLoss: 'Total Forest Loss YoY',
  alertCenter: 'Alert Center',
  regionalHealthScore: 'Regional Health Score',
  highPriority: 'High Priority',
  requiresImmediateAction: 'Requires immediate action',
  mapHub: 'Regional Map Hub',
  critical: 'Critical',
  warning: 'Warning',
  stable: 'Stable',
  mapHint: 'Click markers to view detailed analysis. Red pulse indicates activity in last 7 days.',
  trendTitle: 'Forest Coverage Trend (2019-2024)',
  trendHint: 'Total forest coverage across all monitored mountains in West Java region.',
  recentActivityLogs: 'Recent Activity Logs',
};
