export const DASHBOARD_COPY = {
  heroTitle: 'Pemantauan Satelit Regional',
  heroSubtitle: 'Platform Pengawasan Lingkungan Jawa Barat',
  systemOnline: 'Sistem Aktif',
  mapLoading: 'Memuat peta...',
  lastUpdatedLabel: 'Pembaruan Terakhir:',
  totalForestLoss: 'Total Kehilangan Hutan Tahunan',
  alertCenter: 'Pusat Peringatan',
  regionalHealthScore: 'Skor Kesehatan Wilayah',
  highPriority: 'Prioritas Tinggi',
  requiresImmediateAction: 'Perlu tindakan segera',
  mapHub: 'Pusat Peta Regional',
  critical: 'Kritis',
  warning: 'Waspada',
  stable: 'Stabil',
  mapHint: 'Klik penanda untuk melihat analisis detail. Denyut merah menandakan aktivitas 7 hari terakhir.',
  trendTitle: 'Tren Tutupan Hutan (2019-2024)',
  trendHint: 'Total tutupan hutan seluruh gunung yang dipantau di wilayah Jawa Barat.',
  recentActivityLogs: 'Log Aktivitas Terbaru',
};
